name: Deploy Flask App with Virtualenv

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
          script: |
            pkill -f app.py || true
            cd /home/ubuntu/flask-gha-deploy
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup venv/bin/python app.py > flask.log 2>&1 &

  health-check:
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Check Flask App Health
        run: |
          echo "Waiting for app to start..."
          sleep 5
          curl -f http://${{ secrets.SERVER_HOST }}:5000 || {
            echo "❌ Health check failed!"
            exit 1
          }
          echo "✅ Health check passed!"
