name: Deploy Flask App

on:
  push:
    branches:
      - main

env:
  HEALTHCHECK_URL: http://35.154.189.47:50000

jobs:
  Build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create virtual environment & install dependencies
        run: |
          python3.10 -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

      - name: Run Unit Tests
        run: ./venv/bin/python -m unittest test_app.py

      - name: Deploy Flask Application
        run: |
          nohup ./venv/bin/python app.py > flask.log 2>&1 &

  health:
    needs: Build-test-deploy
    runs-on: self-hosted

    steps:
      - name: Health check
        run: |
          for i in {1..10}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL)
            if [ "$status" == "200" ]; then
              echo "✅ Health check passed"
              exit 0
            fi
            echo "Waiting for service... ($i/10)"
            sleep 5
          done
          echo "❌ Health check failed after multiple retries"
          exit 1
